/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './config.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        tertiary: 'var(--color-tertiary)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-lowest': 'var(--color-surface-lowest)',
        'on-background': 'var(--color-on-background)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-container': 'var(--color-surface-container)',
        card: 'var(--color-card)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '20px',
        'section-gap-mobile': '64px',
        'container-max': '1140px',
        'section-gap-desktop': '120px',
        unit: '8px',
      },
      fontFamily: {
        'headline-sm': ['Playfair Display', 'serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'label-caps': ['Montserrat', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        script: ['Great Vibes', 'cursive'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2' }],
        'headline-md': ['32px', { lineHeight: '1.3' }],
        'headline-sm': ['24px', { lineHeight: '1.4' }],
        'body-lg': ['18px', { lineHeight: '1.6' }],
        'body-md': ['16px', { lineHeight: '1.6' }],
        'label-caps': ['12px', { lineHeight: '1.5', letterSpacing: '0.1em' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
